## YAML Template.
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 1  # Siempre mantener al menos una instancia
  maxReplicas: 2  # Limite máximo de instancias
  targetCPUUtilizationPercentage: 50  # Escalar cuando la CPU alcanza el 50%
 metrics:
  - type: Custom
    name: requests_per_minute
    resource:
      name: custom.metrics.my-app/requests-per-minute
      targetAverageValue: 5  # Escalar cuando hay 20 solicitudes por minuto

